name: GeyserExtensionMover
version: 1.0.0
main: com.example.GeyserExtensionMover
api-version: 1.13
description: Moves GeyserExtensions*.jar into Geyser/extensions automatically
author: AutoGPT

